server:
  port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.178.254.81:3306/his?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 118.178.254.81
    port: 8888

logging:
  level:
    com.neuedu.mapper: debug
